/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nikitos & 3130 (https://sketchfab.com/vrcityphoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/extrasoundpro-e32364a157ac40a8a7ca6c4d1a95ef58
Title: EXTRASOUNDPRO
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import islandScene from '../assets/3d/island.glb'
import { a } from '@react-spring/three'

const Island =(props) => {
    const islandRef = useRef()
    const { nodes, materials } = useGLTF(islandScene)
    return (
        // {Island 3D model from: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907}
        <a.group ref={islandRef} {...props}>
          <mesh
            geometry={nodes.polySurface944_tree_body_0.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.polySurface945_tree1_0.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.polySurface946_tree2_0.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.polySurface947_tree1_0.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.polySurface948_tree_body_0.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.polySurface949_tree_body_0.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.pCube11_rocks1_0.geometry}
            material={materials.PaletteMaterial001}
          />
        </a.group>
      );
}


export default Island;